---
title: "About"
---

Sarah Grabinski received a Bachelor of Arts in Biology with High Honors from Oberlin College. In 2018-2019, she completed a Data Analytics Boot Camp through Case Western Reserve University. She has done field work in Trinidad and was a technician in research laboratories at Lake Forest College, Case Western Reserve University, and the Cleveland Clinic. She also has experience in hospitality management and worked as data analyst for Hilton Hotels & Resorts.

## Research Interests

-   Transcriptomics and RNA Biology

-   Evolutionary Biology, Ecology, and Conservation Genetics

-   Sexual Selection and Mate Choice

-   Genomics and Bioinformatics

## Education

**Oberlin College** \| Oberlin, OH

B.A. in Biology, High Honors \| Sep 2006 - May 2010

**Case Western Reserve University** \| Cleveland, OH

Data Analytics Boot Camp \| Sep 2018 - Mar 2019

## Experience

**Cleveland Clinic** \| Cleveland, OH\
Senior Research Technologist \| Sep 2020 - Aug 2022

**Hilton Hotels & Resorts** \| Cleveland, OH\
Data Analyst \| Sep 2018 - Mar 2020

**Hilton Hotels & Resorts** \| Cleveland, OH\
Food & Beverage Manager \| Sep 2016 - Sep 2018

**Case Western Reserve University** \| Cleveland, OH\
Research Assistant, Licatalosi Lab \| Oct 2010 - Sep 2014

**Lake Forest College** \| Lake Forest, IL\
Research Assistant, Houde Lab \| Jun 2010 - Aug 2010

**UC Riverside** \| Trinidad, West Indies\
Field Assistant, Reznick Lab \| Jan 2008, Jan 2009

## Affiliations

**Sigma Xi Society** \| 2010 - Present

**American Statistical Association** \| 2022 - Present

## Honors

**Hilton Cleveland Downtown General Manager's Award** \| 2018\
Awarded for providing life-saving care to a team member in medical distress

**Manager of the Quarter, Nomination** \| 2017\
Hilton Hotels & Resorts

**Regional Expert, Agilysys Point of Sales System** \| 2017\
Hilton Hotels & Resorts

**Regional Expert, Unifocus Labor Management System** \| 2017\
Hilton Hotels & Resorts

**Leo S. Millar Memorial Prize in Biology** \| 2010\
Awarded for academic excellence and future promise in the field of biology

**Honda Scholar-Athlete Award** \| 2010\
Awarded to a female athlete of the senior class for outstanding athletic achievements as well as leadership skills, academic excellence, and community involvement.
